### ISSUE TITLE
Need to add ``Cleanup`` Firework following ``Pull``

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/mdworks#5]
At the moment, we pull the files resulting from the MD run after it completes, but then we don't actually delete the files on the remote scratch space. For some systems this is fine, but it is better that we clean up after ourselves.

We should add a new `Cleanup` Firework to the workflow that only executes after a completed `Pull`.

**Comment by orbeckst** [comment]
This is necessary for local workstations.

**Comment by orbeckst** [comment]
However, as discussed in #6, there must be safeguards so that in the _worst case_ only generated data is lost. There cannot be any chance that misconfiguration leads to deletions elsewhere.

**Comment by dotsdl** [comment]
Closed by 8740504d13a2ecfb24021dcf3b6eb6259e51b670
